### ISSUE TITLE
Siste versjon - feil med binær-sensor

### ISSUE THREAD

**Issue by kazzkizz** [sindrebroch/ha-flexit#11]
Hei, 
nedgraderte til forrige versjon pga feil med binærsensor. Ved restart av HA kommer data inn fra Flexit, men oppdaterer seg ikke. 
I logg ser jeg feil med binærsensor på et async call - må kjøre en reinstall og reboot for fullverdig melding, skal ordne det straks.

**Comment by sindrebroch** [comment]
Takk for logger, skal kikke på det ved neste anledning

**Comment by sindrebroch** [comment]
@kazzkizz Hvilken Flexit-enhet har du?

**Comment by sindrebroch** [comment]
@kazzkizz Har en pre-release v2.1.4b1 som jeg vil tro fikser problemet. Kunne du testa om den fungerer som forventet nå? Du må skru på "Show beta versions" i HACS for å få opp pre-releases.

**Comment by kazzkizz** [comment]
CL 4. 
Tester med beta-versjon, men fikk samme feil på oppstart. Logg i bunn. 
Har via HACS installert binary_sensor til info, kan denne klusse til noe? 



Logger: homeassistant.components.binary_sensor
Source: custom_components/flexit/binary_sensor.py:141
Integration: Binær sensor (documentation, issues)
First occurred: 15:20:57 (2 occurrences)
Last logged: 15:20:57

    Error adding entities for domain binary_sensor with platform flexit
    Error while setting up flexit platform for binary_sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 522, in _async_write_ha_state
    extra_state_attributes = self.extra_state_attributes
  File "/config/custom_components/flexit/binary_sensor.py", line 141, in extra_state_attributes
    ATTR_ALARM_CODE_B: self.sensor_data.alarm_code_b if self.sensor_data.get("alarm_code_b", 0) > 0 else "No alarm"
AttributeError: 'dict' object has no attribute 'alarm_code_b'

**Comment by sindrebroch** [comment]
Kult, takk for testing. Da ruller jeg den ut i vanlig release etterhvert :)
