### ISSUE TITLE
Failed to set up error

### ISSUE THREAD

**Issue by tomasb82** [sindrebroch/ha-flexit#32]
Hi,

got this erorr "Failed to set up "

log information

Logger: homeassistant.config_entries
Source: custom_components/flexit/api.py:120
Integration: Flexit ([documentation](https://github.com/sindrebroch/ha-flexit), [issues](https://github.com/sindrebroch/ha-flexit/issues))
First occurred: 14:50:07 (1 occurrences)
Last logged: 14:50:07

Error setting up entry Flexit for flexit
Traceback (most recent call last):
  File "/config/custom_components/flexit/api.py", line 112, in api_wrapper
    response = await self._session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/flexit/api.py", line 111, in api_wrapper
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/flexit/__init__.py", line 42, in async_setup_entry
    device_info=await api.device_info(),
  File "/config/custom_components/flexit/api.py", line 170, in device_info
    await self.auth()
  File "/config/custom_components/flexit/api.py", line 138, in auth
    await self.api_wrapper(
  File "/config/custom_components/flexit/api.py", line 120, in api_wrapper
    raise ApiClientException(
custom_components.flexit.api.ApiClientException: Timeout error fetching information from https://api.climatixic.com/Token

**Comment by sindrebroch** [comment]
Hi. Does the issue persist, or was it a one-time only? Seems the API might have been down at that moment?

**Comment by tomasb82** [comment]
It was  for few days. Now after reload it works

**Comment by sindrebroch** [comment]
Good to hear that its back up. Weird that it lasted so long. 

Not really sure how the retry is handled when the original authentication fails. Might look into handling it a bit better, but it seems the issue was API related. The downsides of using the cloud i guess 🤷‍♂️

Closing this for now. Please reopen if it happens again.
