### ISSUE TITLE
Error on load every reboot on HASS

### ISSUE THREAD

**Issue by Adrianni** [sindrebroch/ha-flexit#33]
Flexit always fails to load when HASS is rebooted (due to update or power outtake). The Flexit integration sucesfully loads when i manually reload the integration after the reboot. 

---- **This is from the log:** -----
Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/flexit/api.py:120
Integration: Flexit (documentation, issues)
First occurred: 08:32:30 (1 occurrences)
Last logged: 08:32:30

Error setting up entry Flexit for flexit
Traceback (most recent call last):
  File "/config/custom_components/flexit/api.py", line 112, in api_wrapper
    response = await self._session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/flexit/api.py", line 111, in api_wrapper
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/flexit/__init__.py", line 42, in async_setup_entry
    device_info=await api.device_info(),
  File "/config/custom_components/flexit/api.py", line 173, in device_info
    await self.get(
  File "/config/custom_components/flexit/api.py", line 78, in get
    return await self.api_wrapper(
  File "/config/custom_components/flexit/api.py", line 120, in api_wrapper
    raise ApiClientException(
custom_components.flexit.api.ApiClientException: Timeout error fetching information from https://api.climatixic.com/DataPoints/Values?filterId=%5B%7B%22DataPoints%22%3A%22Pa7186958-eb80-4425-8a0f-34f768155826%3B0%210083FFFFF00000C%22%7D%2C%7B%22DataPoints%22%3A%22Pa7186958-eb80-4425-8a0f-34f768155826%3B0%210083FFFFF00001C%22%7D%2C%7B%22DataPoints%22%3A%22Pa7186958-eb80-4425-8a0f-34f768155826%3B0%210083FFFFF000046%22%7D%2C%7B%22DataPoints%22%3A%22Pa7186958-eb80-4425-8a0f-34f768155826%3B0%210083FFFFF0012DB%22%7D%2C%7B%22DataPoints%22%3A%22Pa7186958-eb80-4425-8a0f-34f768155826%3B0%210083FFFFF0013EC%22%7D%2C%7B%22DataPoints%22%3A%22Pa7186958-eb80-4425-8a0f-34f768155826%3B0%210083FFFFF00002C%22%7D%2C%7B%22DataPoints%22%3A%22Pa7186958-eb80-4425-8a0f-34f768155826%3B0%21Online%22%7D%2C%7B%22DataPoints%22%3A%22Pa7186958-eb80-4425-8a0f-34f768155826%3B0%210083FFFFF000070%22%7D%2C%7B%22DataPoints%22%3A%22Pa7186958-eb80-4425-8a0f-34f768155826%3B0%210083FFFFF0000C4%22%7D%5D

Image from the Integration:
<img width="1609" alt="Flexit error" src="https://user-images.githubusercontent.com/6409815/195584388-f2d3b36d-9273-430f-861a-53f586829f83.png">

Is this a bug in my configuration or the integration itself?

**Comment by sindrebroch** [comment]
I'm not experiencing this myself, but not something that is too easy to debug. 

My guess: It says TimeoutError, and if this happens every time you restart HA, then maybe it is related to all traffic generated when starting HA being too much for your host / router or something else in your setup? If it consistently does not work when you restart, but works when you reload?

**Comment by JanneN9** [comment]
I have also the same issue with Flexit - after rebooting it won't start.  Integration need to be reload - after that it work OK.

Hardware
Raspberry Pi 2

Home Assistant 2023.1.4
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

![FlexitError-02](https://user-images.githubusercontent.com/10402422/212752586-5bd07406-6a89-409a-bd97-86f4a0acd079.JPG)

Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/flexit/api.py:120
Integration: Flexit (documentation, issues)
First occurred: 9:15:14 PM (1 occurrences)
Last logged: 9:15:14 PM

Error setting up entry Flexit for flexit
Traceback (most recent call last):
  File "/config/custom_components/flexit/api.py", line 112, in api_wrapper
    response = await self._session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/flexit/api.py", line 111, in api_wrapper
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/flexit/__init__.py", line 42, in async_setup_entry
    device_info=await api.device_info(),
  File "/config/custom_components/flexit/api.py", line 170, in device_info
    await self.auth()
  File "/config/custom_components/flexit/api.py", line 138, in auth
    await self.api_wrapper(
  File "/config/custom_components/flexit/api.py", line 120, in api_wrapper
    raise ApiClientException(
custom_components.flexit.api.ApiClientException: Timeout error fetching information from https://api.climatixic.com/Token

**Comment by Adrianni** [comment]
My issues went away after a while by itself. I think it went away after i disabled unnecessary integrations. Hence supporting sindrebroch's assumption that the raspberry system is not able to handle all the load during boot.

**Comment by JanneN9** [comment]
Ok. I will check all errors/notice in booting log.  Is there any kind of watchdog system in HA. Like checking after 10 min of restarting that if reload is needed. Or is it even possible to reload "anything" by '*yaml'?

**Comment by sindrebroch** [comment]
@JanneN9 It is possible to reload by yaml, I think I have used the service "homeassistant.reload_config_entry" for this before, but can't remember for sure.

I doubled the timeout to 20 seconds in the latest release ([2.3.2](https://github.com/sindrebroch/ha-flexit/releases/tag/2.3.2)), so you can check if that helps

**Comment by JanneN9** [comment]
Hi. Updated 2.3.2 and restarted HA 3 times after that. Flexit loaded without problem. Thanks.
