### ISSUE TITLE
Unexpected error fetching flexit data: 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF00000C'

### ISSUE THREAD

**Issue by Fugitive470** [sindrebroch/ha-flexit#36]
Flexit Integration version 2.3.3

## Describe the bug

I've been using the HACS/Flexit intergration for a long time, without issues. So a huge thanks

But, since an engineer added an accessary (cooling water battery) the integration gets a "Unexpected error fetching flexit data: 'Pfnnnnn;1!nnnnnnnn055'" error. Which leads to "Error setting up entry Flexit for flexit"

The engineer unplugged the Flexit Nordic S4 unit a number of times, instead of any service shut down
I've uninstalled and reinstalled the integration a few times (and to be honest, I am no expert, so that may be my undoing)

And I need guidance from you, experts

## Configuration

```yaml

Add your logs here.

2 separate log entries below. 

ERROR1:-

This error originated from a custom integration.

Logger: custom_components.flexit
Source: custom_components/flexit/models.py:118
Integration: Flexit (documentation, issues)
First occurred: 2 June 2023 at 22:01:34 (1107 occurrences)
Last logged: 3 June 2023 at 22:57:37

Unexpected error fetching flexit data: 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF00000C'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/flexit/coordinator.py", line 56, in _async_update_data
    return await self.api.sensor_data()
  File "/config/custom_components/flexit/api.py", line 158, in sensor_data
    return FlexitSensorsResponse.from_dict(
  File "/config/custom_components/flexit/models.py", line 245, in from_dict
    home_air_temperature=util.float_sensor(HOME_AIR_TEMPERATURE_PATH),
  File "/config/custom_components/flexit/models.py", line 138, in float_sensor
    return round(float(self._str_sensor(path)), 2)
  File "/config/custom_components/flexit/models.py", line 118, in _str_sensor
    return self.data[VALUES][f"{self.plant}{path}"][VALUE][VALUE]
KeyError: 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF00000C'



ERROR2
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/flexit/api.py:120
Integration: Flexit (documentation, issues)
First occurred: 3 June 2023 at 22:59:17 (1 occurrences)
Last logged: 3 June 2023 at 22:59:17

Error setting up entry Flexit for flexit
Traceback (most recent call last):
  File "/config/custom_components/flexit/api.py", line 112, in api_wrapper
    response = await self._session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/flexit/api.py", line 111, in api_wrapper
    async with async_timeout.timeout(20):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/flexit/__init__.py", line 42, in async_setup_entry
    device_info=await api.device_info(),
  File "/config/custom_components/flexit/api.py", line 170, in device_info
    await self.auth()
  File "/config/custom_components/flexit/api.py", line 138, in auth
    await self.api_wrapper(
  File "/config/custom_components/flexit/api.py", line 120, in api_wrapper
    raise ApiClientException(
custom_components.flexit.api.ApiClientException: Timeout error fetching information from https://api.climatixic.com/Token










`




## Debug log



Add your logs here.



2023-06-05 21:44:35.315 DEBUG (MainThread) [custom_components.flexit] FlexitToken={'access_token': 'cde3vSHmf5mo25kX5OTnnnnnnnnnnnnnnnnnnnnnnnnnnnMDxjdQj3SJA', 'token_type': 'bearer', 'expires_in': 172799, 'userName': 'me@gmail.com', '.issued': 'Mon, 05 Jun 2023 19:44:34 GMT', '.expires': 'Wed, 07 Jun 2023 19:44:34 GMT'}
2023-06-05 21:44:35.429 DEBUG (MainThread) [custom_components.flexit] FlexitDeviceInfo. plant=Pf43f8022-9109-4f4b-962b-0d97595fc426. data={'totalCount': 9, 'values': {'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF00000C': {'value': 'AAS-20:SU=SiUn;APT=HvacFnct21y_A;APTV=2.425;APS=1;', 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF00001C': {'value': '800131-004842', 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF00002C': {'value': 'FW=03.39.03.30:BL=00.05.02.0003;SVS-300.4:SBC=13.24;', 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF000046': {'value': 'POS3.67', 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF000070': {'value': 0, 'valueDate': 1685981056739}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF0000C4': {'value': 3, 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF0012DB': {'value': 'MDL:ASN= POS3.6715/414;HW=51.46.48;', 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF0013EC': {'value': '160100C4A0', 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!Online': {'value': 1, 'valueDate': 1685980973817}}}
2023-06-05 21:44:35.577 DEBUG (MainThread) [custom_components.flexit] FlexitSensorsResponse. plant=Pf43f8022-9109-4f4b-962b-0d97595fc426. data={'totalCount': 21, 'values': {'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!000000001000055': {'value': {'value': 18.03, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': -50.0, 'maxValue': 50.0}, 'valueDate': 1685994140285}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!000000004000055': {'value': {'value': 19.51, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': -50.0, 'maxValue': 80.0}, 'valueDate': 1685993987677}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!000000005000055': {'value': {'value': 2822.0, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 18000.0}, 'valueDate': 1685993773290}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00000000B000055': {'value': {'value': 24.92, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': -50.0, 'maxValue': 80.0}, 'valueDate': 1685994063422}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00000000C000055': {'value': {'value': 2772.0, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 18000.0}, 'valueDate': 1685991520175}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00000003B000055': {'value': {'value': 24.68, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': -50.0, 'maxValue': 80.0}, 'valueDate': 1685994165359}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00000004B000055': {'value': {'value': 24.6, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 50.0}, 'valueDate': 1685993198067}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!001000000000055': {'value': {'value': 0.0, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 15, 'eventState': 0, 'minValue': 0.0, 'maxValue': 100.0}, 'valueDate': 1685981749127}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!001000003000055': {'value': {'value': 74.0, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 15, 'eventState': 0, 'minValue': 0.0, 'maxValue': 100.0}, 'valueDate': 1685981074433}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!001000004000055': {'value': {'value': 70.0, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 15, 'eventState': 0, 'minValue': 0.0, 'maxValue': 100.0}, 'valueDate': 1685981050109}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00100001D000055': {'value': {'value': 0.8823153, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 15, 'eventState': 0, 'minValue': 0.0, 'maxValue': 100.0}, 'valueDate': 1685981097101}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!002000008000055': {'value': {'value': 0.0, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 15, 'eventState': 0, 'minValue': 0.0, 'maxValue': 9999.0}, 'valueDate': 1685981053445}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!002000082000055': {'value': {'value': 0.0, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 15, 'eventState': 0, 'minValue': 0.0, 'maxValue': 9999.0}, 'valueDate': 1685981053772}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00200011D000055': {'value': {'value': 3352.0, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 99999.0}, 'valueDate': 1685981054520}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00200011E000055': {'value': {'value': 4380.0, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 99990.0}, 'valueDate': 1685981054520}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!0050001BD000055': {'value': {'value': 1, 'statusFlags': 0, 'reliability': 0, 'eventState': 0}, 'valueDate': 1685981057245}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!0050001DA000055': {'value': {'value': 0, 'statusFlags': 0, 'reliability': 0, 'eventState': 0}, 'valueDate': 1685981057385}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!01300002A000055': {'value': {'value': 3, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 13, 'eventState': 0}, 'valueDate': 1685981052820}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!03000010E000055': {'value': {'value': 10, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 360.0}, 'valueDate': 1685981055707}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!030000125000055': {'value': {'value': 30, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 1.0, 'maxValue': 360.0}, 'valueDate': 1685981055552}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!03000013E000055': {'value': {'value': 0, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 600.0}, 'valueDate': 1685981057385}}}
2023-06-05 21:44:35.578 ERROR (MainThread) [custom_components.flexit] Unexpected error fetching flexit data: 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!0020007CA000055'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/flexit/coordinator.py", line 56, in _async_update_data
return await self.api.sensor_data()
File "/config/custom_components/flexit/api.py", line 158, in sensor_data
return FlexitSensorsResponse.from_dict(
File "/config/custom_components/flexit/models.py", line 245, in from_dict
home_air_temperature=util.float_sensor(HOME_AIR_TEMPERATURE_PATH),
File "/config/custom_components/flexit/models.py", line 138, in float_sensor
return round(float(self._str_sensor(path)), 2)
File "/config/custom_components/flexit/models.py", line 118, in _str_sensor
return self.data[VALUES][f"{self.plant}{path}"][VALUE][VALUE]
KeyError: 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!0020007CA000055'
2023-06-05 21:44:35.584 DEBUG (MainThread) [custom_components.flexit] Finished fetching flexit data in 0.154 seconds (success: False)
2023-06-05 21:44:56.451 DEBUG (MainThread) [custom_components.flexit] FlexitToken={'access_token': 'uhHqCnnnnnnnnuF4ycdi6Q_6s-mQoWDoVZUoWMHYujRE6i8kR2eT_SokUJJpxmyqU', 'token_type': 'bearer', 'expires_in': 172799, 'userName': 'me@gmail.com', '.issued': 'Mon, 05 Jun 2023 19:44:56 GMT', '.expires': 'Wed, 07 Jun 2023 19:44:56 GMT'}
2023-06-05 21:44:56.543 DEBUG (MainThread) [custom_components.flexit] FlexitDeviceInfo. plant=Pf43f8022-9109-4f4b-962b-0d97595fc426. data={'totalCount': 9, 'values': {'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF00000C': {'value': 'AAS-20:SU=SiUn;APT=HvacFnct21y_A;APTV=2.425;APS=1;', 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF00001C': {'value': '800131-004842', 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF00002C': {'value': 'FW=03.39.03.30:BL=00.05.02.0003;SVS-300.4:SBC=13.24;', 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF000046': {'value': 'POS3.67', 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF000070': {'value': 0, 'valueDate': 1685981056739}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF0000C4': {'value': 3, 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF0012DB': {'value': 'MDL:ASN= POS3.6715/414;HW=51.46.48;', 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!0083FFFFF0013EC': {'value': '160100C4A0', 'valueDate': 1685980973781}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;0!Online': {'value': 1, 'valueDate': 1685980973817}}}
2023-06-05 21:44:56.656 DEBUG (MainThread) [custom_components.flexit] FlexitSensorsResponse. plant=Pf43f8022-9109-4f4b-962b-0d97595fc426. data={'totalCount': 21, 'values': {'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!000000001000055': {'value': {'value': 18.03, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': -50.0, 'maxValue': 50.0}, 'valueDate': 1685994140285}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!000000004000055': {'value': {'value': 19.51, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': -50.0, 'maxValue': 80.0}, 'valueDate': 1685993987677}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!000000005000055': {'value': {'value': 2822.0, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 18000.0}, 'valueDate': 1685993773290}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00000000B000055': {'value': {'value': 24.92, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': -50.0, 'maxValue': 80.0}, 'valueDate': 1685994063422}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00000000C000055': {'value': {'value': 2772.0, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 18000.0}, 'valueDate': 1685991520175}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00000003B000055': {'value': {'value': 24.68, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': -50.0, 'maxValue': 80.0}, 'valueDate': 1685994165359}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00000004B000055': {'value': {'value': 24.6, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 50.0}, 'valueDate': 1685993198067}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!001000000000055': {'value': {'value': 0.0, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 15, 'eventState': 0, 'minValue': 0.0, 'maxValue': 100.0}, 'valueDate': 1685981749127}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!001000003000055': {'value': {'value': 74.0, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 15, 'eventState': 0, 'minValue': 0.0, 'maxValue': 100.0}, 'valueDate': 1685981074433}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!001000004000055': {'value': {'value': 70.0, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 15, 'eventState': 0, 'minValue': 0.0, 'maxValue': 100.0}, 'valueDate': 1685981050109}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00100001D000055': {'value': {'value': 0.8823153, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 15, 'eventState': 0, 'minValue': 0.0, 'maxValue': 100.0}, 'valueDate': 1685981097101}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!002000008000055': {'value': {'value': 0.0, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 15, 'eventState': 0, 'minValue': 0.0, 'maxValue': 9999.0}, 'valueDate': 1685981053445}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!002000082000055': {'value': {'value': 0.0, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 15, 'eventState': 0, 'minValue': 0.0, 'maxValue': 9999.0}, 'valueDate': 1685981053772}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00200011D000055': {'value': {'value': 3352.0, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 99999.0}, 'valueDate': 1685981054520}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!00200011E000055': {'value': {'value': 4380.0, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 99990.0}, 'valueDate': 1685981054520}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!0050001BD000055': {'value': {'value': 1, 'statusFlags': 0, 'reliability': 0, 'eventState': 0}, 'valueDate': 1685981057245}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!0050001DA000055': {'value': {'value': 0, 'statusFlags': 0, 'reliability': 0, 'eventState': 0}, 'valueDate': 1685981057385}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!01300002A000055': {'value': {'value': 3, 'statusFlags': 0, 'reliability': 0, 'presentPriority': 13, 'eventState': 0}, 'valueDate': 1685981052820}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!03000010E000055': {'value': {'value': 10, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 360.0}, 'valueDate': 1685981055707}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!030000125000055': {'value': {'value': 30, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 1.0, 'maxValue': 360.0}, 'valueDate': 1685981055552}, 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!03000013E000055': {'value': {'value': 0, 'statusFlags': 0, 'reliability': 0, 'eventState': 0, 'minValue': 0.0, 'maxValue': 600.0}, 'valueDate': 1685981057385}}}
2023-06-05 21:44:56.657 ERROR (MainThread) [custom_components.flexit] Unexpected error fetching flexit data: 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!0020007CA000055'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/flexit/coordinator.py", line 56, in _async_update_data
return await self.api.sensor_data()
File "/config/custom_components/flexit/api.py", line 158, in sensor_data
return FlexitSensorsResponse.from_dict(
File "/config/custom_components/flexit/models.py", line 245, in from_dict
home_air_temperature=util.float_sensor(HOME_AIR_TEMPERATURE_PATH),
File "/config/custom_components/flexit/models.py", line 138, in float_sensor
return round(float(self._str_sensor(path)), 2)
File "/config/custom_components/flexit/models.py", line 118, in _str_sensor
return self.data[VALUES][f"{self.plant}{path}"][VALUE][VALUE]
KeyError: 'Pf43f8022-9109-4f4b-962b-0d97595fc426;1!0020007CA000055'
2023-06-05 21:44:56.665 DEBUG (MainThread) [custom_components.flexit] Finished fetching flexit data in 0.121 seconds (success: False)

**Comment by Fugitive470** [comment]
Hi @sindrebroch 
Please ask if you need more information from me

And thanks for this integration. I have been very happy with it, until my own upgrade of the Flexit system

**Comment by sindrebroch** [comment]
Hi. Interesting issue, it's probably using different data fields after the upgrade.

Unfortunately I wont have any time to work on this for a while, as I'm pretty busy at the moment.

I can imagine working on this while not owning it might be difficult, and I don't know how different the the data looks. Might give it a try in the future if I can think of a good workflow, but it won't be for a while.

PRs are welcome if someone wants to give it a shot.
