### ISSUE TITLE
Setup error: Unexpected error fetching flexit data

### ISSUE THREAD

**Issue by trygve** [sindrebroch/ha-flexit#37]
## Describe the bug
Hei

Jeg har akkurat fått installert et Flexit Nordic CL4 aggregat.
Prøver å sette opp denne integrasjonen men får feilmelding som vist under.
Ser ut for meg som det kanskje være at integrasjonen forventer å finne en sensor den ikke får, og dermed feiler?

Tilleggsinfo: Aggregatet er kun installert og koblet opp mot Flexit GO, jeg kan styre ting via appen, men teknikker har enda ikke vært her og justert inn anlegget, slik at alt er default verdier. Mulig det kan ha noe å si...

## Debug log

```text

Logger: custom_components.flexit
Source: custom_components/flexit/models.py:118
Integration: Flexit ([documentation](https://github.com/sindrebroch/ha-flexit), [issues](https://github.com/sindrebroch/ha-flexit/issues))
First occurred: June 28, 2023 at 19:27:31 (78 occurrences)
Last logged: 10:23:07

Unexpected error fetching flexit data: 'Pa8181b01-6449-4106-89a9-18e3d88b547a;1!00000003B000055'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/flexit/coordinator.py", line 56, in _async_update_data
    return await self.api.sensor_data()
  File "/config/custom_components/flexit/api.py", line 158, in sensor_data
    return FlexitSensorsResponse.from_dict(
  File "/config/custom_components/flexit/models.py", line 250, in from_dict
    extract_air_temperature=util.float_sensor(EXTRACT_AIR_TEMPERATURE_PATH),
  File "/config/custom_components/flexit/models.py", line 138, in float_sensor
    return round(float(self._str_sensor(path)), 2)
  File "/config/custom_components/flexit/models.py", line 118, in _str_sensor
    return self.data[VALUES][f"{self.plant}{path}"][VALUE][VALUE]
KeyError: 'Pa8181b01-6449-4106-89a9-18e3d88b547a;1!00000003B000055'

```

**Comment by jonathanbower** [comment]
I have the same issue.

**Comment by jonathanbower** [comment]
> I just figured this out. The EXTRACT_AIR_TEMPERATURE_PATH is wrong, not sure why. I have a completely new CL4 unit, perhaps new firmware? Anyway, after some fighting with the climatix api I found the correct value: `EXTRACT_AIR_TEMPERATURE_PATH = ";1!00000005F000055" # Avtrekk`
> 
> For anyone who wants to fix, you need to edit the /config/custom_components/flexit/const.py file.

This worked for me, I also have a completely new CL4 unit. Thanks for this!

**Comment by jussiroberts** [comment]
> I just figured this out. The EXTRACT_AIR_TEMPERATURE_PATH is wrong, not sure why. I have a completely new CL4 unit, perhaps new firmware? Anyway, after some fighting with the climatix api I found the correct value: `EXTRACT_AIR_TEMPERATURE_PATH = ";1!00000005F000055" # Avtrekk`
> 
> For anyone who wants to fix, you need to edit the /config/custom_components/flexit/const.py file.
> 
> @sindrebroch any way for the integration to query for this new value if the original one fails? Also, per https://portal.api.climatixic.com/ there is a notice:
> 
> > Attention:
> > This developer portal is now deprecated. You can continue to use it, as per usual, until its retirement in September 2023, when it will not any more accessible.
> > Please check the climatixic.com release notes for the portal migration.
> 
> Do you know if this api is being deprecated/closed down, or is it just the dev portal?

Hi, how did you figure out the correct value? I have an EcoNordic WH4 and would like to figure out the correct value for the extract air temperature path. Thanks.

**Comment by jhusum** [comment]
I have econordic WH4 myself, with the same issue.

How can we get the correct path?
